---
tproxy-port: 7893
bind-address: "*"
mode: rule
allow-lan: true
log-level: silent
external-controller: 0.0.0.0:9090
external-ui: yacd-gh-pages
unified-delay: true
ipv6: false
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.0/8
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
proxy-providers:
  akun_indonesia:
    type: file
    path: "./proxy_provider/akun_indonesia.yaml"
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
  akun_singapura:
    type: file
    path: "./proxy_provider/akun_singapura.yaml"
    health-check:
      enable: true
      url: http://cp.cloudflare.com/generate_204
      interval: 300
proxy-groups:
  - name: Akun_ID
    type: url-test
    disable-udp: false
    use:
    - akun_indonesia
    url: http://cp.cloudflare.com/generate_204
    interval: 300
    tolerance: 150
  - name: Akun_SG
    type: url-test
    disable-udp: false
    use:
    - akun_singapura
    url: http://cp.cloudflare.com/generate_204
    interval: 300
    tolerance: 150
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://hi.bonds.id/ping
    interval: 300
    use:
    - akun_singapura
  - name: PING
    type: url-test
    use:
    - akun_singapura
    url: http://www.gstatic.com/generate_204
    interval: 600
  - name: FALLBACK
    type: fallback
    use:
    - akun_singapura
    url: http://www.gstatic.com/generate_204
    interval: 600
  
  - name: TrafficAds
    type: select
    proxies:
      - REJECT
      - Akun_ID
      - PING
      - FALLBACK
  
  - name: TrafficPorn
    type: select
    proxies:
      - REJECT
      - Akun_SG
  
  - name: TrafficDirect
    type: select
    proxies:
      - DIRECT
      - Akun_ID
      - PING
      - FALLBACK
      - LOAD-BALANCE

  - name: TrafficChat
    type: select
    proxies:
      - DIRECT
      - Akun_ID
      - PING
      - FALLBACK
      - LOAD-BALANCE
      
  - name: TrafficPortGames
    type: select
    proxies:
      - DIRECT
      - PING
      - Akun_SG
  
  - name: TrafficGaming
    type: select
    proxies:
      - DIRECT
      - PING
      - Akun_SG
  
  - name: TrafficUmum
    type: fallback
    lazy: true
    proxies:
      - Akun_ID
      - PING
      - FALLBACK
      - LOAD-BALANCE
    url: http://www.gstatic.com/generate_204
    interval: 30
    
  - name: TrafficIndo
    type: fallback
    lazy: true
    proxies:
      - Akun_ID
      - PING
      - FALLBACK
      - LOAD-BALANCE
    url: http://www.gstatic.com/generate_204
    interval: 30
    
  - name: TrafficStreaming
    type: select
    lazy: true
    proxies:
      - LOAD-BALANCE
      - Akun_SG
    url: http://www.gstatic.com/generate_204
    interval: 30
    
  - name: TrafficSosmed
    type: select
    lazy: true
    proxies:
      - LOAD-BALANCE
      - Akun_ID
      - Akun_SG
    url: http://www.gstatic.com/generate_204
    interval: 30
    
rules:
  - DST-PORT,22,TrafficDirect
  - RULE-SET,bank,TrafficDirect
  - RULE-SET,chat,TrafficDirect
  - RULE-SET,gaming,TrafficPortGames
  - RULE-SET,game_dl,TrafficGaming
  - RULE-SET,sosmed,TrafficSosmed
  - RULE-SET,streaming,TrafficStreaming
  - RULE-SET,speedtest,TrafficUmum
  - RULE-SET,18+,TrafficPorn
  - RULE-SET,rule_direct,TrafficDirect
  - RULE-SET,videoconference,TrafficSosmed
#Traffic Umum
  - RULE-SET,rule_umum,TrafficUmum
rule-providers:
  rule_direct:
    type: http
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_meta/main/rule_provider/rule_direct.yaml
    interval: 86400
  rule_umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_umum.yaml
    interval: 86400
  18+:
    type: http
    behavior: domain
    path: "./rule_provider/18+.yaml"
    url: https://raw.githubusercontent.com/mametlagii/rule-provider/main/adult.yaml
    interval: 86400
  bank:
    type: http
    behavior: classical
    path: "./rule_provider/bank.yaml"
    url: https://raw.githubusercontent.com/mametlagii/rule-provider/main/bank.yaml
    interval: 86400
  chat:
    type: http
    behavior: classical
    path: "./rule_provider/chat.yaml"
    url: https://raw.githubusercontent.com/mametlagii/rule-provider/main/chat.yaml
    interval: 86400
  gaming:
    type: http
    behavior: classical
    path: "./rule_provider/game.yaml"
    url: https://raw.githubusercontent.com/mametlagii/rule-provider/main/game.yaml
    interval: 86400
  game_dl:
    type: http
    behavior: domain
    path: "./rule_provider/game-dl.yaml"
    url: https://raw.githubusercontent.com/mametlagii/rule-provider/main/game-dl.yaml
    interval: 86400
  sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/sosmed.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_sosmed.yaml
    interval: 86400
  streaming:
    type: http
    behavior: classical
    path: "./rule_provider/streaming.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_streaming.yaml
    interval: 86400
  speedtest:
    type: http
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_speedtest.yaml
    interval: 86400
  videoconference:
    type: http
    behavior: classical
    path: "./rule_provider/videoconference.yaml"
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_videoconferences.yaml
    interval: 86400
